# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13ad60794d3b70792f749d41db353dd458a5448348c194978393d8c4176328822afc9d7616d9683b39650edad5877eb53dd7e3b6c4c01dc4a2adc470ea1b3378

test:
  secret_key_base: 2f72db45d96a715aed824d3e64fb1078f7e16092db83e4a4848639e1177f15b4bac8890c230886b21d3360a29a59e895f6681eb098cb0575b3f89e135beed46e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
